package com.ei.Bean;
// Generated 2018-7-9 22:35:38 by Hibernate Tools 3.2.2.GA


import java.util.Date;

/**
 * Comment generated by hbm2java
 */
public class Comment  implements java.io.Serializable {


     private long id;
     private long multiMediaID;
     private Date date;
     private long fromUser;
     private String content;
     private long toUser;

    public Comment() {
    }

    public Comment(long multiMediaID, Date date, long fromUser, String content, long toUser) {
       this.multiMediaID = multiMediaID;
       this.date = date;
       this.fromUser = fromUser;
       this.content = content;
       this.toUser = toUser;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public long getMultiMediaID() {
        return this.multiMediaID;
    }
    
    public void setMultiMediaID(long multiMediaID) {
        this.multiMediaID = multiMediaID;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public long getFromUser() {
        return this.fromUser;
    }
    
    public void setFromUser(long fromUser) {
        this.fromUser = fromUser;
    }
    public String getContent() {
        return this.content;
    }
    
    public void setContent(String content) {
        this.content = content;
    }
    public long getToUser() {
        return this.toUser;
    }
    
    public void setToUser(long toUser) {
        this.toUser = toUser;
    }




}


