package com.ei.Bean;
// Generated 2018-7-9 22:35:38 by Hibernate Tools 3.2.2.GA


import java.util.Date;
import java.util.HashMap;
import java.util.Map;

/**
 * MultiMedia generated by hbm2java
 */
public class MultiMedia  implements java.io.Serializable {


     private long id;
     private UserResources userResources;
     private String subType;
     private Date date;
     private Map resource = new HashMap(0);

    public MultiMedia() {
    }

	
    public MultiMedia(UserResources userResources) {
        this.userResources = userResources;
    }
    public MultiMedia(UserResources userResources, String subType, Date date, Map resource) {
       this.userResources = userResources;
       this.subType = subType;
       this.date = date;
       this.resource = resource;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public UserResources getUserResources() {
        return this.userResources;
    }
    
    public void setUserResources(UserResources userResources) {
        this.userResources = userResources;
    }
    public String getSubType() {
        return this.subType;
    }
    
    public void setSubType(String subType) {
        this.subType = subType;
    }
    public Date getDate() {
        return this.date;
    }
    
    public void setDate(Date date) {
        this.date = date;
    }
    public Map getResource() {
        return this.resource;
    }
    
    public void setResource(Map resource) {
        this.resource = resource;
    }




}


