package com.ei.Bean;
// Generated 2018-7-9 22:35:38 by Hibernate Tools 3.2.2.GA



/**
 * User generated by hbm2java
 */
public class User  implements java.io.Serializable {


     private long id;
     private String name;
     private String password;
     private UserInfo userInfo;
     private UserResources userResources;

    public User() {
    }

    public User(String name, String password, UserInfo userInfo, UserResources userResources) {
       this.name = name;
       this.password = password;
       this.userInfo = userInfo;
       this.userResources = userResources;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public UserInfo getUserInfo() {
        return this.userInfo;
    }
    
    public void setUserInfo(UserInfo userInfo) {
        this.userInfo = userInfo;
    }
    public UserResources getUserResources() {
        return this.userResources;
    }
    
    public void setUserResources(UserResources userResources) {
        this.userResources = userResources;
    }




}


