package com.ei.Bean;
// Generated 2018-7-9 22:35:38 by Hibernate Tools 3.2.2.GA


import java.util.HashSet;
import java.util.Set;

/**
 * UserResources generated by hbm2java
 */
public class UserResources  implements java.io.Serializable {


     private long id;
     private User user;
     private int balance;
     private Set advice = new HashSet(0);
     private Set video = new HashSet(0);
     private Set dynamic = new HashSet(0);
     private Set message = new HashSet(0);
     private Set favorite = new HashSet(0);
     private Set bill = new HashSet(0);
     private Set focus = new HashSet(0);
     private Set fan = new HashSet(0);
     private Set history = new HashSet(0);
     private Set logging = new HashSet(0);

    public UserResources() {
    }

	
    public UserResources(User user) {
        this.user = user;
    }
    public UserResources(User user, int balance, Set advice, Set video, Set dynamic, Set message, Set favorite, Set bill, Set focus, Set fan, Set history, Set logging) {
       this.user = user;
       this.balance = balance;
       this.advice = advice;
       this.video = video;
       this.dynamic = dynamic;
       this.message = message;
       this.favorite = favorite;
       this.bill = bill;
       this.focus = focus;
       this.fan = fan;
       this.history = history;
       this.logging = logging;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public int getBalance() {
        return this.balance;
    }
    
    public void setBalance(int balance) {
        this.balance = balance;
    }
    public Set getAdvice() {
        return this.advice;
    }
    
    public void setAdvice(Set advice) {
        this.advice = advice;
    }
    public Set getVideo() {
        return this.video;
    }
    
    public void setVideo(Set video) {
        this.video = video;
    }
    public Set getDynamic() {
        return this.dynamic;
    }
    
    public void setDynamic(Set dynamic) {
        this.dynamic = dynamic;
    }
    public Set getMessage() {
        return this.message;
    }
    
    public void setMessage(Set message) {
        this.message = message;
    }
    public Set getFavorite() {
        return this.favorite;
    }
    
    public void setFavorite(Set favorite) {
        this.favorite = favorite;
    }
    public Set getBill() {
        return this.bill;
    }
    
    public void setBill(Set bill) {
        this.bill = bill;
    }
    public Set getFocus() {
        return this.focus;
    }
    
    public void setFocus(Set focus) {
        this.focus = focus;
    }
    public Set getFan() {
        return this.fan;
    }
    
    public void setFan(Set fan) {
        this.fan = fan;
    }
    public Set getHistory() {
        return this.history;
    }
    
    public void setHistory(Set history) {
        this.history = history;
    }
    public Set getLogging() {
        return this.logging;
    }
    
    public void setLogging(Set logging) {
        this.logging = logging;
    }




}


