package com.ei.Bean;
// Generated 2018-7-9 22:35:38 by Hibernate Tools 3.2.2.GA


import java.sql.Date;

/**
 * UserInfo generated by hbm2java
 */
public class UserInfo  implements java.io.Serializable {


     private long id;
     private User user;
     private String iconURL;
     private String signature;
     private boolean gender;
     private Date birthday;
     private String address;
     private String email;

    public UserInfo() {
    }

	
    public UserInfo(User user) {
        this.user = user;
    }
    public UserInfo(User user, String iconURL, String signature, boolean gender, Date birthday, String address, String email) {
       this.user = user;
       this.iconURL = iconURL;
       this.signature = signature;
       this.gender = gender;
       this.birthday = birthday;
       this.address = address;
       this.email = email;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getIconURL() {
        return this.iconURL;
    }
    
    public void setIconURL(String iconURL) {
        this.iconURL = iconURL;
    }
    public String getSignature() {
        return this.signature;
    }
    
    public void setSignature(String signature) {
        this.signature = signature;
    }
    public boolean isGender() {
        return this.gender;
    }
    
    public void setGender(boolean gender) {
        this.gender = gender;
    }
    public Date getBirthday() {
        return this.birthday;
    }
    
    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }




}


